apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tezca

resources:
- namespace.yaml
- tezca-api-deployment.yaml
- tezca-api-service.yaml
- tezca-web-deployment.yaml
- tezca-web-service.yaml
- tezca-admin-deployment.yaml
- tezca-admin-service.yaml
- tezca-worker-deployment.yaml
- tezca-beat-deployment.yaml
- tezca-redis-deployment.yaml
- tezca-redis-service.yaml
- tezca-redis-pvc.yaml
- tezca-es-deployment.yaml
- tezca-es-service.yaml
- tezca-es-pvc.yaml
- tezca-pdbs.yaml
images:
- digest: sha256:0300f2ed0056d43e038934f75d551badc9142e708b7215ccca15c8e0a2e1c932
  name: ghcr.io/madfam-org/tezca/admin
  newName: ghcr.io/madfam-org/tezca/admin
- digest: sha256:a13767422734b0628ac58183d8b31cd0b1885b37589fc5550ef657f289d9d07b
  name: ghcr.io/madfam-org/tezca/api
  newName: ghcr.io/madfam-org/tezca/api
- digest: sha256:e932406b8f05166b6fc02796558583ed0da13e4efe65cc511eed18a2a34c547b
  name: ghcr.io/madfam-org/tezca/web
  newName: ghcr.io/madfam-org/tezca/web
