apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tezca

resources:
- namespace.yaml
- tezca-api-deployment.yaml
- tezca-api-service.yaml
- tezca-web-deployment.yaml
- tezca-web-service.yaml
- tezca-admin-deployment.yaml
- tezca-admin-service.yaml
- tezca-worker-deployment.yaml
- tezca-beat-deployment.yaml
- tezca-redis-deployment.yaml
- tezca-redis-service.yaml
- tezca-redis-pvc.yaml
- tezca-es-deployment.yaml
- tezca-es-service.yaml
- tezca-es-pvc.yaml
- tezca-pdbs.yaml
images:
- digest: sha256:7f581c46e0c7ecd758731f336547f6ad4aef4b8e5d6a36e5c000efac193b95ed
  name: ghcr.io/madfam-org/tezca/admin
  newName: ghcr.io/madfam-org/tezca/admin
- digest: sha256:5470ec6ed72762fc15f57946e96bd5c59498009d20752077b5094f3a2c009440
  name: ghcr.io/madfam-org/tezca/api
  newName: ghcr.io/madfam-org/tezca/api
- digest: sha256:508ec6df658d310575b658e34326c5611ea9222080c527a223be34b02b4e9cec
  name: ghcr.io/madfam-org/tezca/web
  newName: ghcr.io/madfam-org/tezca/web
