apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tezca-es-data
  labels:
    app.kubernetes.io/name: tezca-es
    app.kubernetes.io/part-of: tezca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
